#! configuration/local.yaml

application:
  host: 127.0.0.1
database:
  require_ssl: false
email_client:
  base_url: "http://localhost:80"
  sender_email: "test@gmail.com"
  authorization_token: "dummy-secret-token"

